"""add shipping fields to order

Revision ID: 1d1ae049177f
Revises: 44d5b2245a50
Create Date: 2025-03-21 23:55:50.985637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d1ae049177f'
down_revision = '44d5b2245a50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_address', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('shipping_city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('shipping_state', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('shipping_zip', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('shipping_phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('shipping_phone')
        batch_op.drop_column('shipping_zip')
        batch_op.drop_column('shipping_state')
        batch_op.drop_column('shipping_city')
        batch_op.drop_column('shipping_address')

    # ### end Alembic commands ###
